# Generated by Django 2.0.1 on 2018-01-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_set', models.DateTimeField()),
                ('wall', models.PositiveSmallIntegerField()),
                ('color', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('ORANGE', 'Orange'), ('PINK', 'Pink'), ('YELLOW', 'Yellow'), ('BLACK', 'Black'), ('WHITE', 'White')], max_length=20)),
                ('setter', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=5)),
                ('grade_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
