# Generated by Django 2.0.1 on 2018-01-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20180102_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, default='na', max_length=200),
        ),
    ]
