# Generated by Django 2.0.1 on 2018-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20180104_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.CharField(blank=True, choices=[('3', '3'), ('4', '4'), ('5a', '5a'), ('5b', '5b'), ('5c', '5c'), ('6a', '6a'), ('6a+', '6a+'), ('6b', '6b'), ('6b+', '6b+'), ('6c', '6c'), ('6c+', '6c+'), ('7a', '7a'), ('7a+', '7a+'), ('7b', '7b'), ('>7b', '>7b')], max_length=5),
        ),
    ]
