# Generated by Django 2.0.1 on 2018-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20180105_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='coming_down',
            field=models.BooleanField(default=False),
        ),
    ]
