# Generated by Django 2.0.1 on 2018-03-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_route_coming_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tape',
            field=models.CharField(blank=True, choices=[('GREEN', 'Green'), ('RED', 'Red'), ('BLUE', 'Blue'), ('ORANGE', 'Orange'), ('BLACK', 'Black'), ('WHITE', 'White')], max_length=20),
        ),
    ]
