# Generated by Django 2.0.2 on 2018-03-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_auto_20180304_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='tape',
            field=models.CharField(blank=True, choices=[('ORANGE', 'Orange 3a-4c'), ('GREEN', 'Green 4c-5c'), ('RED', 'Red  5c-6b'), ('BLUE', 'Blue 6a+-6c'), ('BLACK', 'Black 6c-7a+'), ('WHITE', 'White 7b-7c'), ('PINK', 'Pink >7c')], max_length=20),
        ),
    ]
